language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lindelow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lindelow/react-test npm test

after_success:
  - docker build -t lindelow/multi-client ./client
  - docker build -t lindelow/multi-nginx ./nginx
  - docker build -t lindelow/multi-server ./server
  - docker build -t lindelow/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lindelow/multi-client
  - docker push lindelow/multi-nginx
  - docker push lindelow/multi-server
  - docker push lindelow/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: 'docker-complex'
  env: 'docker-complex-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-955320846055'
  bucket_path: 'docker-complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
